### ISSUE TITLE
Can this model run on RTX GPUs?

### ISSUE THREAD

**Issue by hdnh2006** [NVIDIA-AI-IOT/nanosam#1]
Hello guys,

Congratulations for this new repo.

I understand this model is able to run on Jetson devices, but I would like to know if it can run on RTX GPU for testing purposes.

Thanks again for this fantastic job.

**Comment by jaybdub** [comment]
Yes, this model should work across NVIDIA platforms, including RTX GPUs.

Let me know if you run into any issues, happy to address them.

Best,
John
