### ISSUE TITLE
definition of point label

### ISSUE THREAD

**Issue by spacewalk01** [NVIDIA-AI-IOT/nanosam#13]
Hello thank you for your wonderful work! I would like to know definition of point label (0, 1, 2 etc). What is it? is it the object class? or 
is it a specific object id to distinguish it from the other segments? Thanks.

**Comment by zunction** [comment]
Can someone provide an explanation of point labels? This issue is closed but there is no answer for it.

**Comment by spacewalk01** [comment]
The point labels may be

| Point Label | Description |
|:--------------------:|-------------|
| 0 | Background point |
| 1 | Foreground point |
| 2 | Bounding box top-left |
| 3 | Bounding box bottom-right |
