### ISSUE TITLE
Reimplemented nanosam in cpp

### ISSUE THREAD

**Issue by spacewalk01** [NVIDIA-AI-IOT/nanosam#15]
Hello thank  you for providing the source. It is not an issue. I reimplemented it in cpp on visual studio and would appreciate it if you could provide a feedback on my implementation. thank you: [nanosam-cpp](https://github.com/spacewalk01/nanosam-cpp)

**Comment by jaybdub** [comment]
Hi @spacewalk01 ,

This looks awesome!  Hope to test it out soon.

John
