### ISSUE TITLE
good work！

### ISSUE THREAD

**Issue by SoulProficiency** [NVIDIA-AI-IOT/nanosam#20]
what is the difference between nanoSAM and edgeSAM？
where can we get the c/c++ version？

**Comment by jaybdub** [comment]
https://github.com/spacewalk01/nanosam-cpp

@spacewalk01 made a c++ port of nanosam here.

Let me know if this helps!

Best,
John

**Comment by SoulProficiency** [comment]
> https://github.com/spacewalk01/nanosam-cpp
> 
> @spacewalk01 made a c++ port of nanosam here.
> 
> Let me know if this helps!
> 
> Best, John

thanks a lot!
